import ManagerTemplate from "@/components/managerTemplate"
import CashierList from "../cashierList"

export const metadata = {
   title: 'Dashboard | Ordering System',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <ManagerTemplate title="Dashboard" id="dashboard" menuList={CashierList}>
           {children}
       </ManagerTemplate>
   )
}

export default RootLayout

